### ISSUE TITLE
Refactor Duplicated Steps in GitHub Actions Workflow in AcceptanceStage.yml

### ISSUE THREAD

**Issue by MartynovIvan** [vaisakhsasikumar/electron-app-tests#39]
### Task Description

**Task:** Refactor `AcceptanceStage.yml` to eliminate code duplication across the `acceptance_env` and `e2e_env` jobs.

**Objectives:**
- Identify common steps between `acceptance_env` and `e2e_env`.
- Create a shared template or reusable job that encapsulates the common logic and steps.
- Update `acceptance_env` and `e2e_env` to call the new centralized job or template, ensuring maintainability and reducing redundancy.
- Ensure that all functionality remains intact after refactoring.

**Comment by MartynovIvan** [comment]
https://journal.optivem.com/p/acceptance-stage-in-legacy-code/comment/89481255

>>> a) There's some duplication for acceptance_env & e2e_env... any ideas how to handle it?


VJ: In the file https://github.com/vaisakhsasikumar/electron-app-tests/blob/main/.github/workflows/AcceptanceStage.yml I see duplication such as "Github checkout", "Restore Artifacts" and several subsequent steps are duplicated in "acceptance_env" and "e2e_env" - several steps are duplicated. Do you have ideas how to centralize the duplicated stuff?

**Comment by MartynovIvan** [comment]
The `AcceptanceStage.yml` file contains several instances of duplicated code across the `acceptance_env` and `e2e_env` jobs. Below are the identified duplications along with an additional duplication that could be introduced:

#### 1. **Duplicated Steps in `acceptance_env` and `e2e_env`:**
- **GitHub Checkout:** Both jobs include the step to check out the repository.
  ```yaml
  - name: Github checkout
    uses: actions/checkout@v4
  ```

- **Restore Artifacts:** Both jobs restore artifacts from the cache.
  ```yaml
  - name: Restore Artifacts
    uses: actions/cache/restore@v4
    with:
      path: ./MongoDB Query Executor
      key: ${{ runner.os }}-cache-artifact-${{needs.fetch_run_id.outputs.run_id}}
  ```

- **Use Node.js:** Both environments set up Node.js.
  ```yaml
  - name: Use Node.js
    uses: actions/setup-node@v4
    with:
      node-version: 20
  ```

- **Install Dependencies:** Both jobs run the command to install dependencies.
  ```yaml
  - name: Install dependencies
    run: npm ci
  ```

- **Set Permissions for Bash Scripts:** Both jobs set permissions on scripts.
  ```yaml
  - name: Set Permissions to bash scripts
    run: chmod 755 ./automated_testing/*.sh
  ```

- **Run Application Installation:** Both jobs run the installation script.
  ```yaml
  - name: Run application installation
    run: ./automated_testing/install.sh
  ```

- **Start Mock Services:** Both jobs start mock services.
  ```yaml
  - name: Start Mock services
    run: ./automated_testing/mock-start.sh
  ```

- **Stop Mock Services:** Both jobs stop mock services.
  ```yaml
  - name: Stop Mock services
    run: ./automated_testing/mock-end.sh
  ```
